dist: bionic
language: go
go_import_path: github.com/coreos/ignition/v2

go:
  - "1.12.x"
  - "1.13.x"

services:
  - docker

arch:
  - arm64
  - amd64

install: skip

addons:
  apt:
    packages:
    - libblkid-dev

script:
  - ./test
  - docker build -f Dockerfile.validate .
